/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/room3.gltf
*/

import React, { useRef } from 'react'
import { useGLTF,useTexture,useVideoTexture } from '@react-three/drei'
import * as THREE from "three";
import img from "../assets/scene.jpeg";
export function Model(props) {
  const { nodes, materials } = useGLTF('/models/room3.gltf');
 
  return (
    <group {...props} dispose={null}>
      <ambientLight intensity={1}/>
      <group position={[-2.533, 1.683, -1.256]} rotation={[0, -0.764, 0]} scale={0.011}>
        <mesh geometry={nodes.iMac_1001.geometry} material={materials['Mat.008']} />
        <mesh geometry={nodes.iMac_1001_1.geometry} material={materials['Material.004']}  />
      </group>
      <group position={[-2.179, 1.692, -0.917]} rotation={[0, 0.803, 0]} scale={0.205}>
        <mesh geometry={nodes['Keyboard001|group1030983910|Dupli|22'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1075691498|Dupli|58'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1149852049|Dupli|53'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1152190519|Dupli|19'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1180881246|Dupli|50'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1238060299|Dupli|28'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1238428394|Dupli|61'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1272091893|Dupli|35'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1316349499|Dupli|39'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1323238240|Dupli|32'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group145618305|Dupli|23'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1486350934|Dupli|63'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group150579309|Dupli|11'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1529968652|Dupli|6'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1571332333|Dupli|33'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1581414308|Dupli|8'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1589752359|Dupli|26'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1629393722|Dupli|64'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1629609685|Dupli|21'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1675960081|Dupli|12'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1740918352|Dupli|46'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1753917514|Dupli|5'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1754683637|Dupli|40'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1764140354|Dupli|60'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1870575723|Dupli|65'].geometry} material={materials['mat16.006']} />
        <mesh geometry={nodes['Keyboard001|group1899843208|Dupli|36'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1956214489|Dupli|14'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group196400395|Dupli|15'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group1976194690|Dupli|18'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group205302596|Dupli|31'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group2074153597|Dupli|20'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group2085389804|Dupli|57'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group2091112366|Dupli|59'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group2106755496|Dupli|4'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group2146178072|Dupli|38'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group252681800|Dupli|7'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group268332703|Dupli|44'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group287159489|Dupli|13'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group295085766|Dupli|9'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group311988427|Dupli|1'].geometry} material={materials['mat22.011']} />
        <mesh geometry={nodes['Keyboard001|group34220672|Dupli|34'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group384612072|Dupli|10'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group418912012|Dupli|30'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group42243725|Dupli|37'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group425587018|Dupli|'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group449779970|Dupli|3'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group45382983|Dupli|52'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group475225180|Dupli|41'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group573547017|Dupli|49'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group588539140|Dupli|47'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group601803475|Dupli|25'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group616518658|Dupli|56'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group687259746|Dupli|51'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group706802639|Dupli|17'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group729811280|Dupli|48'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group77921105|Dupli|42'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group790925258|Dupli|54'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group801095923|Dupli|29'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group806343109|Dupli|27'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group826580911|Dupli|24'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group873458270|Dupli|55'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group873558583|Dupli|62'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group877249531|Dupli|66'].geometry} material={materials['mat9.002']} />
        <mesh geometry={nodes['Keyboard001|group954813675|Dupli|16'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group96314515|Dupli|2'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group96968687|Dupli|43'].geometry} material={materials['mat21.013']} />
        <mesh geometry={nodes['Keyboard001|group993315105|Dupli|45'].geometry} material={materials['mat21.013']} />
      </group>
      <group position={[-2.119, 1.807, -1.736]} rotation={[Math.PI, -0.642, Math.PI]} scale={0.481}>
        <mesh geometry={nodes['Node-Mesh011'].geometry} material={new THREE.MeshBasicMaterial({ color: 0x482806 })} />
        <mesh geometry={nodes['Node-Mesh011_1'].geometry} material={materials['mat22.006']} />
        <mesh geometry={nodes['Node-Mesh011_2'].geometry} material={materials['mat15.007']} />
        <mesh geometry={nodes['Node-Mesh011_3'].geometry} material={new THREE.MeshBasicMaterial({ color: 0x88f4a5 })}/>
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[-4.117, 1.96, -0.274]} rotation={[0, 0.803, 0]} scale={[0.982, 0.026, 0.286]} />
      <mesh geometry={nodes.Mousepad.geometry} material={materials.Mousepad} position={[-1.864, 1.686, -1.286]} rotation={[-Math.PI, 0.728, -Math.PI]} scale={[0.172, 0.002, 0.21]} />
      <group position={[-1.318, 1.079, -2.092]} rotation={[0, -0.728, 0]} scale={2.122}>
        <mesh geometry={nodes.Cabinet_Bed_Drawer_Tabl_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cabinet_Bed_Drawer_Tabl_2.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Cabinet_Bed_Drawer_Tabl_3.geometry} material={materials.metal} />
      </group>
      <group position={[-4.163, 2.164, -0.085]} rotation={[-Math.PI / 2, 0, 2.414]} scale={[50.247, 45.833, 43.161]}>
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP_1'].geometry} material={materials['Black.081']} />
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP_2'].geometry} material={materials['Brown.033']} />
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP_3'].geometry} material={materials['Plant_Green.033']} />
      </group>
      <group position={[-1.581, 1.500, -0.399]} rotation={[Math.PI, -0.764, Math.PI]} scale={[0.029, 0.032, 0.029]}>
        <mesh geometry={nodes.Chair003_1.geometry} material={materials['Executive.003']} />
        <mesh geometry={nodes.Chair003_2.geometry} material={materials['Executive__1.003']} />
        <mesh geometry={nodes.Chair003_3.geometry} material={materials['Executive__2.003']} />
        <mesh geometry={nodes.Chair003_4.geometry} material={materials['Executive__3.003']} />
      </group>
      <group position={[-2.919, 1.933, -0.796]} rotation={[0, -1.568, 0]} scale={85.615}>
        <mesh geometry={nodes.Light_Desk001_1.geometry} material={materials['Black.097']} />
        <mesh geometry={nodes.Light_Desk001_2.geometry} material={materials['LightMetal.027']} />
        <mesh geometry={nodes.Light_Desk001_3.geometry} material={materials['White.053']} />
      </group>
      <group position={[-2.619, 1.692, -0.896]} rotation={[-Math.PI, -1.318, 0]} scale={56.181}>
        <mesh geometry={nodes.Phone_1.geometry} material={materials['White.001']} />
        <mesh geometry={nodes.Phone_2.geometry} material={materials['Grey.001']} />
        <mesh geometry={nodes.Phone_3.geometry} material={materials['Black.003']} />
      </group>
      <group position={[-2.334, 1.385, -1.096]} rotation={[0, 0.843, 0]} scale={0.032}>
        <mesh geometry={nodes['Node-Mesh003'].geometry} material={materials._5_Drawer} />
        <mesh geometry={nodes['Node-Mesh003_1'].geometry} material={materials._5_Drawer_1} />
      </group>
      <mesh geometry={nodes.Mouse.geometry} material={materials['Material.001']} position={[-1.851, 1.683, -1.282]} rotation={[0, 0.997, 0]} scale={147.364} />
      <group position={[-2.594, 1.716, -0.482]} rotation={[-Math.PI, 0.704, -Math.PI]} scale={2.199}>
        <mesh geometry={nodes['Node-Mesh004'].geometry} material={materials['mat21.001']} />
        <mesh geometry={nodes['Node-Mesh004_1'].geometry} material={materials['mat15.001']} />
      </group>
      <group position={[-0.795, 1.759, -2.46]} rotation={[-Math.PI / 2, 0, 2.414]} scale={100}>
    
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP001_1'].geometry} material={materials['Black.081']} />
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP001_2'].geometry} material={materials['Brown.033']} />
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP001_3'].geometry} material={materials['Plant_Green.033']} />
      </group>
      <group position={[-3.563, 2.153, -0.883]} rotation={[-Math.PI / 2, 0, 2.414]} scale={[50.402, 46.03, 43.702]}>
     
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP002_1'].geometry} material={materials['Black.081']} />
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP002_2'].geometry} material={materials['Brown.033']} />
        <mesh geometry={nodes['Houseplant-bfLOqIV5uP002_3'].geometry} material={materials['Plant_Green.033']} />
      </group>
      
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[-0.877, 0.876, 0.832]} rotation={[0, -0.722, -0.031]} scale={[0.809, 0.64, 0.804]} />
   
      <group position={[-2.65, 3.285, -2.217]} rotation={[Math.PI, -0.668, Math.PI]} scale={[1.067, 0.908, 1.06]}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat23} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat21} />
        <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat0} />
        <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat9} />
        <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat6} />
        <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat13} />
        <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat12} />
        <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat4} />
        <mesh geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat16} />
        <mesh geometry={nodes['Node-Mesh_9'].geometry} material={materials.mat14} />
        <mesh geometry={nodes['Node-Mesh_10'].geometry} material={materials.mat1} />
        <mesh geometry={nodes['Node-Mesh_11'].geometry} material={materials.mat5} />
        <mesh geometry={nodes['Node-Mesh_12'].geometry} material={materials.mat8} />
        <mesh geometry={nodes['Node-Mesh_13'].geometry} material={materials.mat7} />
        <mesh geometry={nodes['Node-Mesh_14'].geometry} material={materials.mat15} />
        <mesh geometry={nodes['Node-Mesh_15'].geometry} material={materials.mat10} />
        <mesh geometry={nodes['Node-Mesh_16'].geometry} material={materials.mat24} />
        <mesh geometry={nodes['Node-Mesh_17'].geometry} material={materials.mat25} />
      </group>
      <group position={[-4.427, 2.761, -0.535]} rotation={[0, -0.761, 0]} scale={[3.031, 2.723, 3.135]}>
        <ambientLight intensity={1}/>
        <mesh geometry={nodes['Node-Mesh001'].geometry} material={materials['mat24.001']} />
        <mesh geometry={nodes['Node-Mesh001_1'].geometry} material={materials.mat20} />
      </group>
      <mesh geometry={nodes['Cup001|Cup|Dupli|'].geometry} material={materials['Mat.006']} position={[-1.938, 1.68, -1.542]} rotation={[-Math.PI, 1.25, -Math.PI]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('/models/room3.gltf')
